# Service1 configuration for dev environment
name: cloud-ops-nodejs-ms
environment: dev
replicaCount: 1
# ServiceAccount configuration for secure AWS access via IRSA
serviceAccount:
  create: true
  name: cloud-ops-nodejs-ms-sa
  annotations:
    # This provides secure access to RDS, S3, Secrets Manager, and Redis/ElastiCache
    # Replace with actual role ARN from Terraform output: terraform output app_full_access_role_arn
    eks.amazonaws.com/role-arn: "arn:aws:iam::035475678676:role/dev-client-name-app-full-access-role"
image:
  repository: 035475678676.dkr.ecr.eu-west-3.amazonaws.com/dev-client-name-services
  tag: "cloud-ops-nodejs-ms-20250603-ce74440"
service:
  port: 8080
ingress:
  enabled: true
  # Complete annotation set (Helm replaces, doesn't merge annotations)
  annotations:
    # Core ALB annotations (required for ALB functionality)
    kubernetes.io/ingress.class: alb
    alb.ingress.kubernetes.io/scheme: internet-facing
    alb.ingress.kubernetes.io/target-type: ip
    # Environment-specific configuration
    alb.ingress.kubernetes.io/group.name: dev-client-name
    alb.ingress.kubernetes.io/healthcheck-path: /health
    alb.ingress.kubernetes.io/listen-ports: '[{"HTTP": 80}]'
    # Use ALB security group created by ALB controller module
    alb.ingress.kubernetes.io/security-groups: "sg-00ea0de692fc221e3"
  hosts:
    # No host restriction - accepts any hostname (including ALB's direct DNS)
    - paths:
        - path: /cloud-ops-nodejs-ms
          pathType: Prefix
autoscaling:
  enabled: false
  # Disabled until metrics server is deployed
  # minReplicas: 1
  # maxReplicas: 3
  # targetCPUUtilizationPercentage: 70
  # targetMemoryUtilizationPercentage: 70
resources:
  limits:
    cpu: 500m
    memory: 512Mi
  requests:
    cpu: 100m
    memory: 128Mi
env:
  - name: NODE_ENV
    value: development
  - name: LOG_LEVEL
    value: debug
  - name: SERVICE_VERSION
    value: "1.0.0"
