# Service1 configuration for dev environment
name: service1
environment: dev

replicaCount: 2

image:
  repository: client/service1
  tag: "latest"

service:
  port: 8080

ingress:
  enabled: true
  annotations:
    alb.ingress.kubernetes.io/group.name: client-dev
    alb.ingress.kubernetes.io/healthcheck-path: /health
  hosts:
    - host: api-dev.example.com
      paths:
        - path: /service1
          pathType: Prefix

autoscaling:
  enabled: true
  minReplicas: 2
  maxReplicas: 5
  targetCPUUtilizationPercentage: 70

resources:
  limits:
    cpu: 500m
    memory: 512Mi
  requests:
    cpu: 100m
    memory: 128Mi

env:
  - name: NODE_ENV
    value: development
  - name: LOG_LEVEL
    value: debug
  - name: SERVICE_VERSION
    value: "1.0.0"

# Redis connection info
envFromSecret: "service1-secrets" 