# Default values for microservices
# This is a YAML-formatted file.

# Service name - MUST be overridden
name: ""

# Environment (dev, staging, prod)
environment: dev

# Replicas for the Deployment
replicaCount: 1

# Docker image configuration
image:
  repository: ""
  pullPolicy: IfNotPresent
  tag: ""

# Optional image pull secrets
imagePullSecrets: []

# Service configuration
service:
  type: ClusterIP
  port: 8080
  annotations: {}

# Ingress configuration for ALB
ingress:
  enabled: false
  annotations:
    # Specific ALB/AWS annotations can be added here
    alb.ingress.kubernetes.io/group.name: ingress-group
    alb.ingress.kubernetes.io/listen-ports: '[{"HTTP": 80}, {"HTTPS": 443}]'
    alb.ingress.kubernetes.io/ssl-redirect: '443'
  hosts:
    - host: chart-example.local
      paths:
        - path: /
          pathType: Prefix
  tls: []

# Resource requests and limits
resources:
  limits:
    cpu: 500m
    memory: 512Mi
  requests:
    cpu: 100m
    memory: 128Mi

# Horizontal Pod Autoscaler
autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 5
  targetCPUUtilizationPercentage: 80
  targetMemoryUtilizationPercentage: 80

# Liveness and readiness probes
livenessProbe:
  enabled: true
  path: /health
  initialDelaySeconds: 30
  periodSeconds: 10
  timeoutSeconds: 5

readinessProbe:
  enabled: true
  path: /health
  initialDelaySeconds: 30
  periodSeconds: 10
  timeoutSeconds: 5

# Node selector, affinity, and tolerations
nodeSelector: {}
affinity: {}
tolerations: []

# Environment variables
env: []
# - name: ENV_VAR_1
#   value: value1

# Optional secret name for environment variables
envFromSecret: "" 