# Default values for microservices
# This is a YAML-formatted file.

# Service name - MUST be overridden
name: ""

# Environment (dev, staging, prod)
environment: dev

# Replicas for the Deployment
replicaCount: 1

# Docker image configuration
image:
  repository: ""
  pullPolicy: IfNotPresent
  tag: ""

# Optional image pull secrets
imagePullSecrets: []

# ServiceAccount configuration for IRSA (IAM Roles for Service Accounts)
serviceAccount:
  # Create a ServiceAccount for this application
  create: false
  # Name of the ServiceAccount (defaults to release name if not specified)
  name: ""
  # Annotations for the ServiceAccount (use this for IRSA role ARN)
  annotations: {}
  # Example IRSA annotation:
  # annotations:
  #   eks.amazonaws.com/role-arn: "arn:aws:iam::123456789:role/my-app-role"

# Service configuration
service:
  type: ClusterIP
  port: 8080
  annotations: {}

# Ingress configuration for ALB
ingress:
  enabled: false
  # All ALB annotations are now centralized here for better management
  annotations:
    # Core ALB annotations (required for ALB functionality)
    kubernetes.io/ingress.class: alb
    alb.ingress.kubernetes.io/scheme: internet-facing
    alb.ingress.kubernetes.io/target-type: ip
    
    # Default configuration (override these in environment-specific values)
    alb.ingress.kubernetes.io/group.name: default-ingress-group
    alb.ingress.kubernetes.io/listen-ports: '[{"HTTP": 80}]'
    alb.ingress.kubernetes.io/healthcheck-path: /health
    
    # SSL configuration (uncomment and configure as needed)
    # For HTTPS setup, uncomment the following:
    # alb.ingress.kubernetes.io/listen-ports: '[{"HTTP": 80}, {"HTTPS": 443}]'
    # alb.ingress.kubernetes.io/ssl-redirect: '443'
    # alb.ingress.kubernetes.io/certificate-arn: arn:aws:acm:region:account:certificate/cert-id
    
    # Security group (override with actual security group ID from Terraform output)
    # alb.ingress.kubernetes.io/security-groups: sg-xxxxxxxxxxxxxxxxx
  hosts:
    - host: chart-example.local
      paths:
        - path: /
          pathType: Prefix
  tls: []

# Resource requests and limits
resources:
  limits:
    cpu: 500m
    memory: 512Mi
  requests:
    cpu: 100m
    memory: 128Mi

# Horizontal Pod Autoscaler
autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 5
  targetCPUUtilizationPercentage: 80
  targetMemoryUtilizationPercentage: 80

# Liveness and readiness probes
livenessProbe:
  enabled: true
  path: /health
  initialDelaySeconds: 30
  periodSeconds: 10
  timeoutSeconds: 5

readinessProbe:
  enabled: true
  path: /health
  initialDelaySeconds: 30
  periodSeconds: 10
  timeoutSeconds: 5

# Node selector, affinity, and tolerations
nodeSelector: {}
affinity: {}
tolerations: []

# Environment variables
env: []
# - name: ENV_VAR_1
#   value: value1

# Optional secret name for environment variables
envFromSecret: "" 